# Generated by Django 5.2.1 on 2025-09-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
