# Generated by Django 5.2.1 on 2025-06-29 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_menuitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='in_cart',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
