# Generated by Django 5.2.1 on 2025-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
